files_unchanged:
  - .github/workflows/linting.yml
  - assets/multiqc_config.yaml
  - assets/sendmail_template.txt
  - lib/NfcoreSchema.groovy
  - docs/README.md
files_exist:
  - .github/markdownlint.yml
  - bin/markdown_to_html.py
actions_awsfulltest: False
