# conda env create -f environment.yml
name: reporting
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # python version
  - python=3.8.3

  # conda packages
  - numpy=1.20.*
  - pandas=1.2.*
  - conda-forge::upsetplot=0.4.4
