# conda env create -f environment.yml
name: packages
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # python version
  - python=3.8.3

  # conda packages
  - pandas=1.3.3
  - dask=2021.9.1
